added functionality regarding #13
GIScience/openrouteservice-app pull request #101
Opened 2017-06-10 18:33 UTC by TheGreatRefrigerator

2017-06-10 20:30 UTC, TimMcCauley requested changes
Two suggestions for a simpler implementation.

2017-06-10 20:30 UTC, TimMcCauley commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.html
> +        <input id="color-{{$index}}" name="orsRouteColor" ng-click="$ctrl.changeColor($index)" ng-model="$ctrl.extrasCheck[$index]" type="checkbox">
`ng-model="$ctrl.extrasCheck[$index]"` can instead be a simple boolean of the checkbox, $ctrl.extrasChecked should suffice.. check my comment below for further information

2017-06-10 20:30 UTC, TimMcCauley commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.js
> +            ctrl.changeColor = (i) => {
With the previously mentioned setup you can simply pass the boolean to `changeColor(bool)` and add/remove the geometries depending on its value. Maybe instead of changeColor call it addRouteExtrasToMap() or sth similar? `ctrl.extrasCheck = [];` shouldn't be needed,  the loop also not, if I'm not mistaken.

2017-06-10 21:55 UTC, TheGreatRefrigerator commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.js
> +            ctrl.changeColor = (i) => {
@TimMcCauley The Loop and the extrasCheck list are for the purpose of only selecting one checkbox at a time: if you had selected waytypes and now want to select steepness other boxes get deselected.
Is that possible with the boolean version? I would need an identifier for the checked boxes, but they get created in an ng-repeat, so if i just name it ctrl.extrasChecked -> all checkboxes will be checked/unchecked at the same time.
I don't see how this will work otherwise -.-

2017-06-11 08:11 UTC, TimMcCauley commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.js
> +            ctrl.changeColor = (i) => {
Valid point, this will only work if we use a closed scope. Suggestion: to tackle this issue and make the code a little cleaner and more structured, how about adding the logic a new child component (like `ors-bars-chart`) -  we could call it `ors-route-extras-map`?

2017-06-11 11:19 UTC, TheGreatRefrigerator commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.js
> +            ctrl.changeColor = (i) => {
sounds good to me, but how do i actually do that? adding ors-route-extras.js -> put the html for the checkbox into the template of it -> put code for addRouteExtrasToMap() into controller (similar to `ors-bars-chart`) -> tweak everything until it works ?

2017-06-11 12:11 UTC, TimMcCauley commented on app/components/ors-panel-routing/ors-route-extras/ors-route-extras.js
> +            ctrl.changeColor = (i) => {
Basically the same procedure as ors-bars-chart but use a component instead of directive. Pass the data to the component, so something like
`<ors-route-extras-map key="obj.type" obj="obj.data" ></ors-route-extras-map>`

2017-06-13 13:09 UTC, closed without merging